/*
 * This file is generated by jOOQ.
 */
package io.github.onotoliy.ofiles.jooq.tables.records;


import io.github.onotoliy.ofiles.jooq.tables.OfilesInfo;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OfilesInfoRecord extends UpdatableRecordImpl<OfilesInfoRecord> implements Record11<UUID, String, UUID, LocalDateTime, LocalDateTime, String, String, String, Long, UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>OFILES_INFO.UID</code>. Уникальный идентификатор
     */
    public void setUid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>OFILES_INFO.UID</code>. Уникальный идентификатор
     */
    public UUID getUid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>OFILES_INFO.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>OFILES_INFO.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>OFILES_INFO.AUTHOR</code>.
     */
    public void setAuthor(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>OFILES_INFO.AUTHOR</code>.
     */
    public UUID getAuthor() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>OFILES_INFO.CREATION_DATE</code>.
     */
    public void setCreationDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>OFILES_INFO.CREATION_DATE</code>.
     */
    public LocalDateTime getCreationDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>OFILES_INFO.DELETION_DATE</code>.
     */
    public void setDeletionDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>OFILES_INFO.DELETION_DATE</code>.
     */
    public LocalDateTime getDeletionDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>OFILES_INFO.ORIGINAL_NAME</code>.
     */
    public void setOriginalName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>OFILES_INFO.ORIGINAL_NAME</code>.
     */
    public String getOriginalName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>OFILES_INFO.CONTENT_TYPE</code>.
     */
    public void setContentType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>OFILES_INFO.CONTENT_TYPE</code>.
     */
    public String getContentType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>OFILES_INFO.EXTENSION</code>.
     */
    public void setExtension(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>OFILES_INFO.EXTENSION</code>.
     */
    public String getExtension() {
        return (String) get(7);
    }

    /**
     * Setter for <code>OFILES_INFO.SIZE</code>.
     */
    public void setSize(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>OFILES_INFO.SIZE</code>.
     */
    public Long getSize() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>OFILES_INFO.ACCOUNT</code>.
     */
    public void setAccount(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>OFILES_INFO.ACCOUNT</code>.
     */
    public UUID getAccount() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>OFILES_INFO.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>OFILES_INFO.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<UUID, String, UUID, LocalDateTime, LocalDateTime, String, String, String, Long, UUID, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<UUID, String, UUID, LocalDateTime, LocalDateTime, String, String, String, Long, UUID, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return OfilesInfo.OFILES_INFO.UID;
    }

    @Override
    public Field<String> field2() {
        return OfilesInfo.OFILES_INFO.NAME;
    }

    @Override
    public Field<UUID> field3() {
        return OfilesInfo.OFILES_INFO.AUTHOR;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return OfilesInfo.OFILES_INFO.CREATION_DATE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return OfilesInfo.OFILES_INFO.DELETION_DATE;
    }

    @Override
    public Field<String> field6() {
        return OfilesInfo.OFILES_INFO.ORIGINAL_NAME;
    }

    @Override
    public Field<String> field7() {
        return OfilesInfo.OFILES_INFO.CONTENT_TYPE;
    }

    @Override
    public Field<String> field8() {
        return OfilesInfo.OFILES_INFO.EXTENSION;
    }

    @Override
    public Field<Long> field9() {
        return OfilesInfo.OFILES_INFO.SIZE;
    }

    @Override
    public Field<UUID> field10() {
        return OfilesInfo.OFILES_INFO.ACCOUNT;
    }

    @Override
    public Field<String> field11() {
        return OfilesInfo.OFILES_INFO.DESCRIPTION;
    }

    @Override
    public UUID component1() {
        return getUid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UUID component3() {
        return getAuthor();
    }

    @Override
    public LocalDateTime component4() {
        return getCreationDate();
    }

    @Override
    public LocalDateTime component5() {
        return getDeletionDate();
    }

    @Override
    public String component6() {
        return getOriginalName();
    }

    @Override
    public String component7() {
        return getContentType();
    }

    @Override
    public String component8() {
        return getExtension();
    }

    @Override
    public Long component9() {
        return getSize();
    }

    @Override
    public UUID component10() {
        return getAccount();
    }

    @Override
    public String component11() {
        return getDescription();
    }

    @Override
    public UUID value1() {
        return getUid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public UUID value3() {
        return getAuthor();
    }

    @Override
    public LocalDateTime value4() {
        return getCreationDate();
    }

    @Override
    public LocalDateTime value5() {
        return getDeletionDate();
    }

    @Override
    public String value6() {
        return getOriginalName();
    }

    @Override
    public String value7() {
        return getContentType();
    }

    @Override
    public String value8() {
        return getExtension();
    }

    @Override
    public Long value9() {
        return getSize();
    }

    @Override
    public UUID value10() {
        return getAccount();
    }

    @Override
    public String value11() {
        return getDescription();
    }

    @Override
    public OfilesInfoRecord value1(UUID value) {
        setUid(value);
        return this;
    }

    @Override
    public OfilesInfoRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public OfilesInfoRecord value3(UUID value) {
        setAuthor(value);
        return this;
    }

    @Override
    public OfilesInfoRecord value4(LocalDateTime value) {
        setCreationDate(value);
        return this;
    }

    @Override
    public OfilesInfoRecord value5(LocalDateTime value) {
        setDeletionDate(value);
        return this;
    }

    @Override
    public OfilesInfoRecord value6(String value) {
        setOriginalName(value);
        return this;
    }

    @Override
    public OfilesInfoRecord value7(String value) {
        setContentType(value);
        return this;
    }

    @Override
    public OfilesInfoRecord value8(String value) {
        setExtension(value);
        return this;
    }

    @Override
    public OfilesInfoRecord value9(Long value) {
        setSize(value);
        return this;
    }

    @Override
    public OfilesInfoRecord value10(UUID value) {
        setAccount(value);
        return this;
    }

    @Override
    public OfilesInfoRecord value11(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public OfilesInfoRecord values(UUID value1, String value2, UUID value3, LocalDateTime value4, LocalDateTime value5, String value6, String value7, String value8, Long value9, UUID value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OfilesInfoRecord
     */
    public OfilesInfoRecord() {
        super(OfilesInfo.OFILES_INFO);
    }

    /**
     * Create a detached, initialised OfilesInfoRecord
     */
    public OfilesInfoRecord(UUID uid, String name, UUID author, LocalDateTime creationDate, LocalDateTime deletionDate, String originalName, String contentType, String extension, Long size, UUID account, String description) {
        super(OfilesInfo.OFILES_INFO);

        setUid(uid);
        setName(name);
        setAuthor(author);
        setCreationDate(creationDate);
        setDeletionDate(deletionDate);
        setOriginalName(originalName);
        setContentType(contentType);
        setExtension(extension);
        setSize(size);
        setAccount(account);
        setDescription(description);
    }
}
