/*
 * This file is generated by jOOQ.
 */
package io.github.onotoliy.ofiles.jooq;


import io.github.onotoliy.ofiles.jooq.tables.OfilesInfo;
import io.github.onotoliy.ofiles.jooq.tables.OfilesParameters;
import io.github.onotoliy.ofiles.jooq.tables.records.OfilesInfoRecord;
import io.github.onotoliy.ofiles.jooq.tables.records.OfilesParametersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OfilesInfoRecord> PK_OFILES_INFO = Internal.createUniqueKey(OfilesInfo.OFILES_INFO, DSL.name("PK_OFILES_INFO"), new TableField[] { OfilesInfo.OFILES_INFO.UID }, true);
    public static final UniqueKey<OfilesParametersRecord> PK_OFILES_PARAMETERS = Internal.createUniqueKey(OfilesParameters.OFILES_PARAMETERS, DSL.name("PK_OFILES_PARAMETERS"), new TableField[] { OfilesParameters.OFILES_PARAMETERS.UID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<OfilesParametersRecord, OfilesInfoRecord> OFILES_INFO_PARAMETERS = Internal.createForeignKey(OfilesParameters.OFILES_PARAMETERS, DSL.name("OFILES_INFO_PARAMETERS"), new TableField[] { OfilesParameters.OFILES_PARAMETERS.INFO_UID }, Keys.PK_OFILES_INFO, new TableField[] { OfilesInfo.OFILES_INFO.UID }, true);
}
