/*
 * This file is generated by jOOQ.
 */
package io.github.onotoliy.ofiles.jooq;


import io.github.onotoliy.ofiles.jooq.tables.OfilesInfo;
import io.github.onotoliy.ofiles.jooq.tables.OfilesParameters;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>OFILES_INFO</code>.
     */
    public static final OfilesInfo OFILES_INFO = OfilesInfo.OFILES_INFO;

    /**
     * The table <code>OFILES_PARAMETERS</code>.
     */
    public static final OfilesParameters OFILES_PARAMETERS = OfilesParameters.OFILES_PARAMETERS;
}
